---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: imdbgraph-secrets
  namespace: imdbgraph
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCA6LV3hvJ+bOmuFywJEYa4VjfEFT+69+kYeBjoaCkdPSy2f/jYrY0aN6qx9wAfcE3XHnF3vgPnsw21FgnV9NPggvqB0G9oRtSriVuVyuXjAoEMsB7SiLIdCIHBgTRbnk2BbfANf7X6hYv5NrrWcmMiY8aWF3KpSoyGT6qxI1v9LATgQ94IyiNyieq18OAGgo6bnb6X7nzKSiUqpCYgHR2Gex/vdbWLBpKIrzgAO8fy6oBDEhsOtmsvOMqNDWy4zpzRb7ryai1Z5acyguAStsHDSkTDxKVGQ0PyjmSFosP8D1bJSMUFlvyHQ1VTk5q261hMP1/c32Ld3xTsZZ+jt//+/zvxm9ThYlM2nfvW+0WwE22zjzyPSZnb7v+XZz4eMQ1aRPmGXPKbiZwuNFOjsxSV3SLUGRnS6FBtAg/u0AGQNgflQ2xGtHQO2FZvYIa/UYPc0cbfGD5E5iNa4zJ0OmuCnnVxNxLNjlmc7k4i20ziKjvYNgPgXfDu8OtmuI5hwKexoAY4mXsHfPQH/vKhTrXeXaEkQ/rYpaElOq6YF1oIaPwS0b1aV8yR1n4GeF9VwF90fbPHCkW6QOJ3PQc0YiaUrmhKdxnl1ZHvsbLSr17u8+7zu7oSSfryQy6srde/j7w+KxXW6Lrtr9/5y1jZIDAInLTMrnf//YQmjN6y4p8rNEwvFCSOyhyMhX25he/sKU3DkWPvnvf9M/W13J9fzV9wNcBTag==
    OMDB_KEY: AgBJxTUI5OjpVWfxO/IDwrF09c/ESs/wuQf1cNdTzatfA6G6Ak7yaC5Nw8SOwOc4Xt5ljXM+XiR5jC9bPbQFSAanWf+phYnmGn8R7gA8DXnjDyrhAAqxS8gryW3djSpIhgUpBR3SiZEMJiiGbmPpviGA1JetLLeEONfipUgctAbiERHTLaIY7dUNxz+a0opgRM4Tf8O6LJMeE18BKwwA8dpL619PC1oiTvLHTgf0fbSTsGSPLw+L7i/1VCnVapLUWMrrZzVfCQqwjMYxuSQdUgsdjwpLMfvQy+k1ojw6D1Rk05Ya9Xnp25CDE2fA5WI9sll0rGVZ05T0J1xyNsuIIauCV4vCeE4sFgGuezUJoZ+aQfwR3sAN8WMargMyZk0swjrehf28Lks6fea8iy1vs1+27ydD0VNH8dw0vvjc6cvdLF2AgFQBUAJctAAOag/BzcVmQnz5pEoQNjjwUqHC+ZhaX6rPmdBcgsEhedjLRdJmipOz5zezrRCQEKonI9OpW67CJKOvtF1k6ePPDoi3Wfhg1dP+O1UlPT24TFPC0PgJ4hSIxWxdOo3HDKEfqGTa61LuVSHbEelYUB0yWgXy5jWkAHZtVWrfxbQrEv8sqqHcgXLWpHBlPkJSQdsqKNUwu9nBxr+j/bmldKPISGjn+Kx+Cg6+Sm3IkJ1OyklHsPlJjmltnLbfQW1WDbTTQOMfRVgThnD2Ujokkg==
  template:
    metadata:
      creationTimestamp: null
      name: imdbgraph-secrets
      namespace: imdbgraph
