---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: imdbgraph-secrets
  namespace: imdbgraph
spec:
  encryptedData:
    DATABASE_PASSWORD: AgAhNIFgVEH00r/rO9yzIUkkKKJHccHAnUug3U0l6CCClUUoPLFx7s6+bI5TqUYHpnIJJ9nwxhYDSRxdwLGImSXP1KQWes/ccGR/scsYtIAT9Cy9UXzJaqN7w2uEFBNpXdQLHJVi3pzmSIPL4j/6lser3prlpo/OOwoX7c86QpZyf9OTZ1RNXIn04FHdEPiADBwDmYJsHvv4FXszPzzn3zrf8i1BUkNJLl75DfuVNt4ayRH2xTfZ26nslkFnqH8oDxqOG5uGguva22qhLpOX4zZFCaRr6oZ5+ao2sZcm9yLjg33g/y56shN24uEidDLKEso9A7LXVeQwcVEcKnq2AJRFlFn6KEncW+ypPDWBntbD/GLAc4YnDawJT2trg1GwpCDypYrGVGmugwNncdg494Bg9rO0TontH/Q/2r2KnlJzXRBXjigOgXukc1k9WE4xxMzjDUTApHWs1A55bH7E29hF6jpvYOdbkSDgOFU4ofQE41+jF9QdmquTw1+AHRDNZ87YHIICQWMnNdh7z9q3gtdtFr2a8Jh8bD9m3LVFfoeCvNLFUr5uNeQI9jnuhunq3aKjDxQC+D/EeekBhD2uBK5mcXgk2NEpxmuDOtVhQkpz7NYVFdc+g+TJc3VO2EzqzEVaX4mnrU+Jij42bwEiTDXtMjgjelnis0+M+mPEQD21wx+MKUu//jNRebuVla95aqja/EpJGSLmqA==
    OMDB_KEY: AgCutF4+Rr+NN12qPCmyC8+F9Qzj80ixVLuv+nwLhCoUOQylQqbNzLIK2W4OLqMRLJqJSSLTNDT4omtTV5dYDN559HbzVDWJLH18JxuZuQk0wgCyITGK94RRB3sOQ49i6YvLJaFhq4VKYObHXQiLAnNPZesUhTaAp9L3zH4HYzJcRVFSLqZxPH0KhooEP0eNVWpdY5jYaEUtikvD9E3FVq2V53rRlLEj+pmpj8L+8QjirDyMaApuQsLBbeeQ0oL9XC5DUrVy+T24ZwTPxHalNXEcOAONZWictVtopFGT5pa3y2eNiPmOIZGLPNSeIMM6rKGs7ADwH+MGYLDPOyeX0TpAsf4pLTwKxzGuKcCqntqWzk5k7AUusfvw4ykRpfJeVv6oOUGHEYybuwTnPQZRTcMJkHa1vsZk3vB7FODeFj+LA8z8TdgirEJHSDLLA3rf1eLSswXiKFVkuy1GQwt0nyTloelE9VZ51UYoTPtnOs5emvIgNE8IiFifHfQVr6zy30uwFDp6N3hp6mhchbdZ8CcLOaLdokQOYczqRyDEm4gvMYEBl2+Bw72iLyYJ0MKMBRp9WbCf/dCfH6DG5COoPnPNKuMMnO9WkcR6/8u/G4aCHyrWBnatOqVgXBpOqxmrHDUSt/NMP/pcr/y8uyEkOj/jzT25f5lCMAwyMKai3AcGKRRnz50Yu1VRLeZqj9rmyzjvu/F/xTqTYQ==
  template:
    metadata:
      creationTimestamp: null
      name: imdbgraph-secrets
      namespace: imdbgraph
