---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: imdbgraph-secrets
  namespace: imdbgraph
spec:
  encryptedData:
    DATABASE_PASSWORD: AgAtTsmJd+lOjoL7FIxRA1BjkVm1rxwWshlqYTS3GC7XrK5lHKBHjQ0luamKAWvHLH2XtcNomhrcbq/YjdqHfzo6SKFaV7EGaRtbLFO5ATSzw2pJgZYj6TJluIpYnM64tii17UGECwqtK3qkAa0dNOvYQQUNz0i0XlGLmVBnBCQWBkowaAGc2fz47bnbolkzMvlobJd4JSREml7iQA/JCB1XHq5DRAlfWVoYF8VZrzGA4Y2Z5GAW7h4amSzyVWuUF904hxqJZe6eK4fQ6hjDh4+CM265bzuYMl4f5SCTAh2id86JFVCG5IgT3ICIFkNEYxOa3zJIoIR7R+ENJwoSn+GoOntlxviP+0dBjJVk6yvIo3GSqaFz5r03pFtYRylJO0d1yhbs+ZVoPd+qIvRx3NR8ghEhtg7Th4Z1TrTHd2fkrfFS5UM0oJFws+jEqa+xgNjKymrdA3F0iXMXc2Nhz4w6BXmtPCSC+xCw9vb7MddyQTNnyEcjf3sbmO1n+jP6P2MpgSpNHSFGkprargF2ek3m4c5SdO6CoKGDCUolJPAzLKuDdoGn//Ovh8RK+WQUGrYBDvzYFd3QylMIQF081Qaoq0GfXFiRL72FpxZ5uzkIep8X31hDM5u0yt6NZKKsEBXUx8ydFM5sn2GnwkQ3aMArjQfqbEoo7Vc02gt2sn8u5zL9JdOIzqfbXSZ3x8akyCXoy77f64RQW7nqKjhos8RulNc=
    OMDB_KEY: AgAU4yJmIFJmOUVotxqg3NOrOexGfKx6G6J3Cr3QIxO/qcCLoNvKE+X0OFWSJxWvT5IDNU7cE6gKPgIIwrc5dJ530rMAlWEzw0LeO1HMvTVIzPKn2aE1jNYc4Ya4tMKROyStrx/RkgXwsjbMo2bE9FIj9knEDbB2ZsyCh/HPoeNPP6JtFzE4f434L/aboM6OvwwW6rYVbkmG5Ft8wPJgs9aX0ioXXo+J2Wp6C3XCcKCr/Mc/fQfP8bxU+VJ5utY7ufQ3n9+/XKb1pTlHgjgIL/kEiTP2Yfr0k2tycGGhXf2DvIO4cxUeA5MNz0hXwxdzkWurb2gIjP6DneOgH5PotDqZcdfmXz9Q0CxhFxZs24FVo0xDpByV+2RaJI/KlvKztAns4XjvPW5oJu4Sr8rttT3ad/I3W/HOJstr0Ope6xbzvOO8PynDAdiq4/c6Mtb4+OoNj9raSFRc9im8WAUfpvFcmsWZYKQ8kXt1jThXqVzjXdl4Lwyb6Cykqn3PiHIhjbuRbbUE2+OTmVFnqLEtAJEeKt3j8dtWMQEw0eI45aEoJftXcS8yvrHix812UCeiFX0P+8Cjmr+OhvG2FPrjWo5n0xKB7Ue+OkchzN69wShSS6i+dbBGPLZEj68zhetC+m07hsYGcwzauhw6GxnDzGBjAXEJDgksRjY7DXBhCVBKXQmNJMJz0kv6BgvbAYgSKBN7j/kXohHtSQ==
  template:
    metadata:
      creationTimestamp: null
      name: imdbgraph-secrets
      namespace: imdbgraph
