apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - patch: |-
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
    target:
      kind: Issuer
      name: letsencrypt
      namespace: networking
      group: cert-manager.io