apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: imdbgraph
resources:
  - ../base
  - sealed-secret.yaml
configMapGenerator:
- name: imdbgraph-config
  literals:
    - DATABASE_HOST=db-imdbgraph.postgres.database.azure.com
    - DATABASE_NAME=postgres
    - DATABASE_USER=postgres
