---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: imdbgraph-secrets
  namespace: imdbgraph
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCl8Fai3H8f+S2aqjsFpiOktp3DVncaRwgHzvUKCsBuReVEDvo3rWjCw5QzD02qXmUTXbCIgqOz2t4R+TvOm6W5XcOcqBccTDQlmzEjuwIrXhl3Cx0h1R23KfBSPGXTa3gjb80LQygIQkSzpBBU3ek3TrbUEDiCT1VRLMhbhK4x6yHcJxOF1P/69873fBEmXeQnx6PIsyrpHWF3nFwoHb5IBkTOZgRYfWZTT4fmSxW+ScfnA3lZD0qR3sNlZPcrPucAMcred07VTEWI8Aif7jk8IcHfJRHaaM7BBB0l4SJ+eVbOwIwmtK4jUkmYXqi23/mheGEfLNQYQ4F8hR8+SWhZW2XJs3zn5XT/W6JJCLz+AeZD/FHtMiUFE4xmlCtymwQgfxDgXfpaF5U/KK9EqEl5T0Z93a+kkcoQCFG4ofHOG21t3KNv1xdjnkGGCUd1IWSOqShvKfLRsn21lYm2NCygOLJ0oDkLzdvR5jwprxGpM8wwD/qtKtR/yq16xY7YIiJfLIsg/KkwL5YQp3PNKnzQKHQnG4tZyRMbKdQok45hZU+P6SmIQCxQAoiOPMTcqqKGKwYpor/Q6hvVEcJCi5nm6ZERWcPUS2UeVpYLUWY+OhqRyl2V3Ua31+SEKu5lkvA9Wmwjw+lnF/OWiE1RL/1lobjLoYDTfZWPTHy+X4jWs1sacFKEJ3yY3ouT2+RUJS1xYbHrCE7zbg==
    OMDB_KEY: AgDGElk3/N8l5PPwkQ2xc00anrZDtHA79/VO4x1n/kBvBuzmegpzI/YBGpti7TXQWgEOZ6tMiPILIGbtoUCy1uYRYK+l6DQWyh0qT5EJL+Y1CVNJX1CfCImOFObR46t3eShgCFAaXZyBQrMVsnhghrrafTKBT1/rZmBHbngL708e2CkxISNjRNXYBqVPbDyV0yb0EnCDYl8Uw0b3ph+5HeN0SlfVSD6WMtS3Qc348/gDVuDb1R5+Y6okfT4NQRORGLocVqDIdY2a3K4ICPehCf2vu81WjOm2v7Si6e789eNfsDNiu2450IrePN1GPC813qYdzCLQ5IfB6OQnSP6FogRCnkglU5zWjumwBJYhe2uh6cegj5itqowlDanJYvgiNI8ecSCuzJ4pnkzoMa2suS3GHZQux2HaibFTUBaCiw4Z2kK5KywucMkkCl67b2dJjLxUdMUhtGSJVhC78jWJSuX/r0pnS9RDYovQaDffjSneXrq4Zk5S6vtZ8DcU3A0ol9ZyCrbHZ+87Jq4u9FTH0jV6iLP5Q72+NMYicXBuyrsAKA21dPyE5PqPhH4T8d0/vg8hjjljwWNag7TJ1K7U7B8QyZqZpVDBgwxMas4lav8MgQWHOkeeg4f3CnBLKP4Ol1AaKt9MAZ07aBDxUcwLmfgDKbWuxGR/DJYVh6LAAbUvP+JnZ6yr59S+7jizj4FHwaTYN5ikEmvXHw==
  template:
    metadata:
      creationTimestamp: null
      name: imdbgraph-secrets
      namespace: imdbgraph
