---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: imdbgraph-secrets
  namespace: imdbgraph
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCb4A0w3RHrxIKTHNkyILQgkfHHFI+w3waKFgxLncAGnxYQCloi8pd3A8HWX5rjSMehz5ifaw25WTJNvwVkeXa2KPV/etj9TspCI4zXdhAf14gii1ERBZNPMMH+edNF3kjy4oB5N9sKREsY8kuCKwfsE3YxUEyu/lrKdIRAvx6kfRaHfosIFfZDDyvdFnBdndpYz7mXCfJJek3NxbdWzboFq25ydrLrZmv6sEb8ThPrnNuC7fD87Mu+fpwYwwKcgx7K55LXUtwBkRBMrCTsJxXCBSqh40iGTRRnPq5Up5klLGhoWZoXJzsztmEz2Ig9CdWalnYfg71QxtVVpWZQRDCVAwaStHOER3SolsrTJup+V9YF6CxEO439p55oqrJI3VbWVRx8wzW4emavvH2xM6eypIFwkNUITHCzLHlJ97jgVgyPyvPijIMaKTLVxXqWjAFIa/l1NBBfVyhYzbw7sI5yHHKNZDWcmdsXY4+011vyFN1n+v+6PSGy/5Zi6rmmwendOSM/pc4R6mx5BusCxHCwwYrWRHg/uMbJWqLcWv7zMW8+wB8IcV4+HyZRFOjh89H41KoB4CHVsQUBLCU2AtOwaKGdw2fYkpgrSn56XvDavcCWZmGw7U8d6Yybfm70hmhl1Vm7qJhw6HrnWStZ8QyoqwYJxwYA5xgl0qCTI+6DGY7fa+mLwi1fGv5oSHpDAoDZGCiim8yOOA==
    OMDB_KEY: AgAfVcce1FOLQ2tAB2eU5M2BBU7F5/TEVI2N/aiGQxdjggC+fNqUgicTLg5a40uiAzcYBSkushu8648CouEpBrjANr+hCKlS7shZ7ZYvCmmYAuwxBiAIy1RGUy1LqpTctmiiEb/FKl5vQQt1LflQQKzGsukpuf//OOfqnsuDmI+Dx4sy5mCjB4UCaVxzsWVJyB97YNWWuJmeLTfCtcEm/L8wd3MF5SUHtIuqma9CoA6ZZABnf7rilK/OdOpTXqMwEwQfjfQAgXJlbNDBv3q8eQj6bqjlkRgG+pEvJtc7aP1UOtIjC3vxKrr8DHJyi1ojCld+mCRT8rgAi25ApwOjXuPIgvfipe3Pa6/k2l6tJDG3/Fjnr1pK+Zd7ILui/Jipb5pPfEsNOpcVYFElBrwWhr10+HU78rTSO2NK1jzOp1CPJwcn4STl1ESHaaqY8RnLLwT6AOd8+BKniDpW91h4pJ7tyWX+TK6ngxPJJngiizuPaGCPZQK1DwDj06zWniuELv03nxTJYUZcSQ9BhWRUGZy9vb4GIODhV/OLCA2zFcRhlLfgggNOqGRdzlqiA2uheKjD4WTxgrlyG1r8jeCRGmJjgEaqdSy2aBUyvE52LYmhpLRsZ+zVazFnhBrkBrXVx3vCBHkLztiuunS8GYApUm2PPzA7RYe2Htj6OA06InHCqHntan217EyeNnU9nmEp/uSEosG3NdiSZA==
  template:
    metadata:
      creationTimestamp: null
      name: imdbgraph-secrets
      namespace: imdbgraph
