---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: imdbgraph-org
  namespace: networking
spec:
  secretName: imdbgraph-org-tls
  dnsNames:
    - api.staging.imdbgraph.org
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: networking
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-issuer-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: traefik-gateway
                namespace: networking
                kind: Gateway